### ISSUE TITLE
New versoin will not get fetched by regular install

### ISSUE THREAD

**Issue by DominikBuchner** [VascoElbrecht/JAMP#24]
Hi, 
when installing JAMP as outlined in the README it still installs v0.77. Any way to quick-fix this?

best Dominik

**Comment by VascoElbrecht** [comment]
Dear Dominik,

version number is not updated in the package description. If you install with install_github("VascoElbrecht/JAMP", subdir="JAMP") it pulls things from the "master" brach which is the latest version (even if R still shows it as 0.77). Sorry about that. Will make sure to update R version numbers with the next release =)

Best
Vasco
