### ISSUE TITLE
make empty folder to drop demultiplexed files in

### ISSUE THREAD

**Issue by VascoElbrecht** [VascoElbrecht/JAMP#3]
(in case one has already demultplexed files)

**Comment by VascoElbrecht** [comment]
This function was added `Empty_folder()`

**Comment by marcelpolling** [comment]
hi @VascoElbrecht, just a short question as I'm pretty new at trying your JAMP. I have it installed and received demultiplexed files from the sequencing company (D250237_COI_L001_R1_001.fastq is the naming). I put them in this Empty_folder() in the _data section and then just run Merge_PE() right..? For some reason I get the error that it cannot find the files.. is there a way of pointing to where they are?
