### ISSUE TITLE
Bold_web_hack: Make %tage filtering on below order level

### ISSUE THREAD

**Issue by VascoElbrecht** [VascoElbrecht/JAMP#8]
In rare cases, ~50-70% matches are returned from bold, and thus NA should be given as a hit rather than a taxonomy.

**Comment by karl-cottenie** [comment]
I don't know how to work with github just yet, but I have been playing around with your JAMP code a little bit. I thought your Bold_web_hack was a very nice way to get the identification, but I also thought that with webscraping it should be possible to avoid the copy-paste step of your function. I attached an R script that does this using functionality from the package "rvest". The only thing you have to do is change the link in the read_html statement with the link that BOLD emails you. Maybe you can take a look at my code, see if it works for you, and maybe if it is an alternative to your function?

[2018-12-07 Bold_web_hack_alternative.txt](https://github.com/VascoElbrecht/JAMP/files/2658874/2018-12-07.Bold_web_hack_alternative.txt)

**Comment by VascoElbrecht** [comment]
Hey Karl,

Looks very interesting = ) Thank you! I will certainly take a look next week! Could you submit this as a pull request? This way you can get credit for your contributions to JAMP.

Also, let me know how JAMP is working for you and if you have any other questions. It still have a long way to go especially documentation wise! Happy about any feedback, both positive and negative.

Best
Vasco

**Comment by VascoElbrecht** [comment]
This was implemented in the web hack. Kals improvements to the web hack will be added in the future (further discussion in the pull request). Thanks Karl.
